# Generated by Django 5.0.1 on 2024-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_featuredcar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredcar',
            old_name='car_model',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='featuredcar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='featuredcar',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='image',
            field=models.ImageField(upload_to='featured_cars_images/'),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='main_traits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='year',
            field=models.IntegerField(),
        ),
    ]
