# Generated by Django 5.0.1 on 2024-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_car_model_featuredcar_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcar',
            name='time_period',
            field=models.CharField(default='Default Time Period', max_length=50),
        ),
        migrations.AlterField(
            model_name='featuredcar',
            name='image',
            field=models.ImageField(upload_to='featured_cars/'),
        ),
    ]
