# Generated by Django 5.0.1 on 2024-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_featuredcar_time_period_alter_featuredcar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcar',
            name='time_period',
            field=models.CharField(max_length=50),
        ),
    ]
