# Generated by Django 5.0.1 on 2024-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_featuredcar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcar',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
